- alias: 'Exterior Lighting on when dark outside'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: switch.turn_on
    entity_id: switch.outdoor_light

- alias: 'Exterior Lighting off at midnight'
  trigger:
    platform: time
    at: '23:50:00' 
  action:
    service: switch.turn_off
    entity_id: switch.outdoor_light

#- alias: 'Living room light on when arriving home at night'
#  trigger:
#    platform: zone
#    entity_id: device_tracker.francesosiphone
#    zone: zone.home
#    event: enter
#  action:
#    service: switch.turn_on
#    entity_id: switch.living_room_light